#!/bin/sh
# usage (from the root): sh tools/build_text.sh <name> <original game file>  -> builds/<name>.gb + .sav + .ips
# Fast path when ONLY the translation/scene*.tsv changed: starts from builds/pre-reloc.gb (generated by the
# last build_all.sh, already with font, menus, resources and title) and redoes only the scene relocation.
# If anything else changed (fixed.tsv, names.tsv, intro, glossary, scripts), use build_all.sh.
set -e
N=${1:?build name}
[ -f builds/pre-reloc.gb ] || { echo "builds/pre-reloc.gb does not exist: run build_all.sh first"; exit 1; }
perl tools/checktsv.pl translation/scene*.tsv | tail -1
perl tools/reloc.pl builds/pre-reloc.gb builds/$N.gb translation/scene*.tsv | grep -v '^scene .*: bank'
cp builds/teste.sav builds/$N.sav; echo "test save copied (builds/teste.sav)"
ORIGINAL_ROM=${2:-$ORIGINAL_ROM}; [ -n "$ORIGINAL_ROM" ] && [ -f "$ORIGINAL_ROM" ] || { echo "usage: sh tools/build_text.sh <name> <original game file>   (or set ORIGINAL_ROM)"; exit 1; }
perl tools/mkips.pl "$ORIGINAL_ROM" builds/$N.gb builds/$N.ips
